name: my_todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  sqflite: ^2.3.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - images/welcome.png
    - images/welcome2.png
    - images/profile.png
    - images/password.png
    - images/todo_icon.png
    - images/todo_icons.png
    - images/todo_icon2.png
    - images/selected.png
    - images/not_selected.png
